# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('shorturl', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('originalurl', models.CharField(max_length=300)),
            ],
        ),
    ]
